# Generated by Django 6.0.6 on 2026-07-11 00:56

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert_alert_created_id_idx_and_more'),
        ('artifacts', '0002_artifact_artifact_created_id_idx'),
        ('cases', '0002_case_case_created_id_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(django.db.models.functions.comparison.Coalesce('last_seen_time', 'first_seen_time', 'created_at', output_field=models.DateTimeField()), name='alert_event_time_expr_idx'),
        ),
    ]
