services:
  postgres:
    image: postgres:latest
    container_name: asp-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresk-password-for-agentic-soc-platform
      POSTGRES_DB: asp
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql